### ISSUE TITLE
Some helpful tutorials

### ISSUE THREAD

**Issue by chalalala** [chalalala/Automatic-Speaker-Recognition#1]
I have no idea of what we are going to do so just do some research on the Internet :'D Feel free to give any suggestions :'D
Here are some links I think that could be helpful
[Automatic Speaker Recognition using Transfer Learning](https://towardsdatascience.com/automatic-speaker-recognition-using-transfer-learning-6fab63e34e74)
[Identifying speakers with voice recognition](https://subscription.packtpub.com/book/big_data_and_business_intelligence/9781787125193/9/ch09lvl1sec61/identifying-speakers-with-voice-recognition)

**Comment by Syrus123** [comment]
https://www.mathworks.com/matlabcentral/fileexchange/?category[]=1735&s_tid=FX_AO_detail_cat

**Comment by Syrus123** [comment]
http://www.ifp.illinois.edu/~minhdo/teaching/speaker_recognition/

**Comment by chalalala** [comment]
https://medium.com/analytics-vidhya/building-a-speaker-identification-system-from-scratch-with-deep-learning-f4c4aa558a56

**Comment by chalalala** [comment]
https://appliedmachinelearning.blog/2017/11/14/spoken-speaker-identification-based-on-gaussian-mixture-models-python-implementation/

**Comment by chalalala** [comment]
https://github.com/orchidas/Speaker-Recognition?fbclid=IwAR1AawOKVETRzHT94wDJTF2n1GWMZUou9nzmIb1T5S210dMu1pGszxv8NZ8

**Comment by chalalala** [comment]
https://github.com/crouchred/speaker-recognition-py3
