### ISSUE TITLE
Add code to get testing voice from microphone

### ISSUE THREAD

**Issue by chalalala** [chalalala/Automatic-Speaker-Recognition#2]
The testing voice must be taken from the microphone then resampling with a suitable rate (16kHz)

**Comment by tungnv2k** [comment]
Do you have a microphone to integrate?

**Comment by chalalala** [comment]
Yes?

**Comment by chalalala** [comment]
Anw, these might help
https://realpython.com/python-speech-recognition/#working-with-microphones
https://stackoverflow.com/questions/30619740/downsampling-wav-audio-file

**Comment by chalalala** [comment]
https://stackoverflow.com/questions/35344649/reading-input-sound-signal-using-python
Oh, this code looks better (the second one). It has sampling together with recording.

**Comment by chalalala** [comment]
Sorry I was too excited to wait for you so I did it myself teehee :'D
